In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/Users/berk/Desktop/IstDataAcademy/Github/Data-Science-Project-1/Open_Restaurant_Applications.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13765 entries, 0 to 13764
Data columns (total 35 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   objectid                                  13765 non-null  int64
 1   globalid                                  13765 non-null  object
 2   Seating Interest (Sidewalk/Roadway/Both)  13765 non-null  object
 3   Restaurant Name                           13764 non-null  object
 4   Legal Business Name                       13764 non-null  object
 5   Doing Business As (DBA)                   13753 non-null  object
 6   Building Number                           12776 non-null  object
 7   Street                                    13765 non-null  object
 8   Borough                                   13765 non-null  object
 9   Postcode                                  13765 non-null  int64
 10  Business Address                          13765 non-null  object
 11  Food Service Establishment Permit #       13759 non-null  object
 12  Sidewalk Dimensions (Length)              11576 non-null  float64
 13  Sidewalk Dimensions (Width)               11576 non-null  float64
 14  Sidewalk Dimensions (Area)                11576 non-null  float64
 15  Roadway Dimensions (Length)               8753 non-null   float64
 16  Roadway Dimensions (Width)                8753 non-null   float64
 17  Roadway Dimensions (Area)                 8753 non-null   float64
 18  Approved for Sidewalk Seating             13765 non-null  object
 19  Approved for Roadway Seating              13765 non-null  object
 20  Qualify Alcohol                           13765 non-null  object
 21  SLA Serial Number                         9114 non-null   object
 22  SLA License Type                          9115 non-null   object
 23  Landmark District or Building             13765 non-null  object
 24  landmarkDistrict_terms                    2039 non-null   object
 25  healthCompliance_terms                    13765 non-null  object
 26  Time of Submission                        13765 non-null  object
 27  Latitude                                  12463 non-null  float64
 28  Longitude                                 12463 non-null  float64
 29  Community Board                           12463 non-null  float64
 30  Council District                          12463 non-null  float64
 31  Census Tract                              12463 non-null  float64
 32  BIN                                       12372 non-null  float64
 33  BBL                                       12372 non-null  float64
 34  NTA                                       12463 non-null  object
dtypes: float64(13), int64(2), object(20)
memory usage: 3.7+ MB

In [4]:
df.head()

,objectid,globalid,Seating Interest (Sidewalk/Roadway/Both),Restaurant Name,Legal Business Name,Doing Business As (DBA),Building Number,Street,Borough,Postcode,...,healthCompliance_terms,Time of Submission,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,13610,{FD87ABAA-860E-4762-845D-8F0403D0246B},roadway,MADAME BONTE,BEANHOUSE LLC,MADAME BONTE,NaN,318 EAST 84 STREET,Manhattan,10028,...,yes,06/09/2022 04:26:00 PM,40.776277,-73.952051,8.0,5.0,138.0,1049941.0,1.015460e+09,Yorkville
1,5900,{3B07E4C0-07B7-4079-8333-64446CC3EE03},sidewalk,Seasoned Vegan,"Seasoned Vegan, LLC","Seasoned Vegan, LLC",55,St. Nicholas Avenue,Manhattan,10026,...,yes,06/26/2020 08:38:00 PM,40.800500,-73.952507,10.0,9.0,216.0,1054995.0,1.018220e+09,Central Harlem South
2,13018,{137C575D-DC14-4F9D-83D9-A3FFE513B3B8},sidewalk,AMERICAS CAFE &amp; GRILL,68TH GRILL INC,AMERICAS CAFE &amp; GRILL,NaN,1159 3 AVENUE,Manhattan,10065,...,yes,10/22/2021 11:01:00 AM,40.766845,-73.962708,8.0,4.0,118.0,1043896.0,1.014220e+09,Lenox Hill-Roosevelt Island
3,11630,{15270732-2A78-4C24-89DD-BE8DD916F115},roadway,SUSHI SEKI,SEKI INC,SUSHI SEKI,undefined,208 WEST 23 STREET,Manhattan,10011,...,yes,12/14/2020 07:54:00 PM,40.744338,-73.996240,4.0,3.0,91.0,1014129.0,1.007720e+09,Hudson Yards-Chelsea-Flatiron-Union Square
4,13137,{EF9C8173-91D1-496E-8BD4-B02BEADC2A21},roadway,Sami &amp; Susu,AMIR NATHAN,Sami & Susu,NaN,190 ORCHARD STREET,Manhattan,10002,...,yes,12/22/2021 12:46:00 PM,40.722124,-73.988160,3.0,1.0,3001.0,1005393.0,1.004120e+09,Chinatown

In [6]:
df['Seating Interest (Sidewalk/Roadway/Both)'].value_counts()

both           6928
sidewalk       4648
roadway        1825
openstreets     364
Name: Seating Interest (Sidewalk/Roadway/Both), dtype: int64